name: CI
on:
  pull_request: ~
  schedule:
    # 12:30 UTC is at 8:30 or 9:30 EST depending on DST
    - cron: '30 12 * * *'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build container image
        run: docker-compose build

      - name: Run tests
        run: docker-compose run --rm tests pytest --cov --cov-fail-under=100

      - name: Run isort
        run: docker-compose run --rm tests isort . --check --diff

      - name: Run flake8
        run: docker-compose run --rm tests flake8

      - name: Run mypy
        run: docker-compose run --rm tests bash -c "mypy datapunt_api/ --strict | mypy-baseline filter"
