name: CI
on:
  pull_request: ~
  schedule:
    - cron: '30 8 * * *'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build container image
        run: docker-compose build

      - name: Run tests
        run: docker-compose run --rm tests python runtests.py
